### ISSUE TITLE
Google Colab compatibility

### ISSUE THREAD

**Issue by arashash** [lebrice/Sequoia#128]
Hi. I was wondering how can we install and use this in Colab? since currently, the Colab python version is 3.6, and Conda environment is not supported well.

I think a full pip installation without Anaconda would be highly appreciated.

Thanks

**Comment by lebrice** [comment]
HI @arashash , thanks for posting!

Sequoia currently targets python >= 3.7, I'd have to look into it, but it might be less work to figure out how to upgrade the python version used by Colab?

As for pip release, yes for sure, I'm going to get this to happen as soon as I can. We'd set it up as part of a basic CI/CD pipeline (#96 )

**Comment by arashash** [comment]
Hi @lebrice 

Woow we are so lucky. Google Colab just updated to 3.7!

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">🐍🎉 Colab has updated to Python 3.7! 🎉🐍<br><br>We&#39;ve (finally) updated the default python version in Colab for all users. Try it out today! <a href="https://t.co/wrcSz6pQsQ">pic.twitter.com/wrcSz6pQsQ</a></p>&mdash; Colaboratory (@GoogleColab) <a href="https://twitter.com/GoogleColab/status/1365062244225060865?ref_src=twsrc%5Etfw">February 25, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by arashash** [comment]
As for the pip release, I would reallyy appreciate it since setting up Conda in Colab is a mess!

Also, I was going to start the continual learning competition and this is a barrier for me since currently, I do not have access to a personal computer or server. So Colab is my only affordable option.

**Comment by lebrice** [comment]
You can still pip install through git though, in the meantime:
```
pip install git+https://www.github.com/lebrice/Sequoia.git
```

**Comment by lebrice** [comment]
that's weird.. What version of `pyyaml` do you have installed? (you can get this through `pip list | grep pyyaml`

**Comment by arashash** [comment]
![image](https://user-images.githubusercontent.com/15813444/110514680-9ab9d400-8118-11eb-9deb-987bb63dad03.png)

Btw I'm using this notebook to test.
https://colab.research.google.com/drive/171qiCxKa14KqhZZ2c8hVpI_c7hh7rMTZ

**Comment by lebrice** [comment]
Ah, here's the issue:
```console
(... somewhere in the pip install log)
ERROR: pytorch-lightning 1.2.3 has requirement PyYAML!=5.4.*,>=5.1, but you'll have pyyaml 3.13 which is incompatible.
```

The problem is that the default runtime in Colab already comes with an older version of pyyaml. I'll fix this (at least temporarily) by increasing our required version.

For now, the simple fix is to manually update `pyyaml`, using `!pip install --upgrade pyyaml`

**Comment by arashash** [comment]
Awesome. Thank you so much. Really excited to start the competition now.
