### ISSUE TITLE
If Sequoia throws an error, jobs with Wandb run forever

### ISSUE THREAD

**Issue by lebrice** [lebrice/Sequoia#153]
Title sounds like a Haiku.
@optimass Does this happen only with `sequoia_sweep` ? or also with plain `sequoia --setting (...)` ? 

Feel free to add any useful info if you have some. I'll try to reproduce this somehow.

**Comment by optimass** [comment]
it seems to be related to my cluster setup. Will update you later

**Comment by lebrice** [comment]
Duplicate of #155
