### ISSUE TITLE
transforms

### ISSUE THREAD

**Issue by LilioISnotAfox** [lebrice/Sequoia#179]
Hello, I wonder how can I in method change the tranforms directly (for example resize(224,224) ? I notice that in class increment setting ,there's only a few ways of transforms.
https://github.com/lebrice/Sequoia/blob/ca9592b1beee1850373acdc362b1411a308cafb2/sequoia/settings/passive/cl/class_incremental_setting.py#L187

**Comment by lebrice** [comment]
Hello @LilioISnotAfox, thanks for posting!


You can modify the `train_transforms`, `val_transforms`, etc. fields on the Setting, and you can either use one of the available Transforms, or you can add your own callable to the list. (You would normally do this inside the `configure()` method of your Method class btw)

I'll update the type annotation of this field so it correctly reflects this.

Be mindful though that the transforms you put in theses lists could also be called with `gym.Space` objects as inputs! 
This is so we can get the impact the transformation will have on the observation space when creating the Setting / environments. This is also why I created this `Transform` class in the first place.

Hope this helps!

**Comment by LilioISnotAfox** [comment]
> Hello @LilioISnotAfox, thanks for posting!
> 
> You can modify the `train_transforms`, `val_transforms`, etc. fields on the Setting, and you can either use one of the available Transforms, or you can add your own callable to the list. (You would normally do this inside the `configure()` method of your Method class btw)
> 
> I'll update the type annotation of this field so it correctly reflects this.
> 
> Be mindful though that the transforms you put in theses lists could also be called with `gym.Space` objects as inputs!
> This is so we can get the impact the transformation will have on the observation space when creating the Setting / environments. This is also why I created this `Transform` class in the first place.
> 
> Hope this helps!

Thanks, it helps!
