### ISSUE TITLE
SettingProxy with multiprocessing dataloader bug

### ISSUE THREAD

**Issue by wwd29** [lebrice/Sequoia#204]
When I use setting proxy to train a method, like [ExampleMethod](https://github.com/lebrice/Sequoia/blob/master/examples/clcomp21/classifier.py), it will create more processes than usual.
It seems something wrong with the multiprocessing dataloader. And I got errors while the main process did **not** be stopped. 
```
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7efbfcb47af0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1324, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1316, in _shutdown_workers
    if w.is_alive():
  File "/usr/lib/python3.7/multiprocessing/process.py", line 160, in join
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
```
However, when i directly define a method, everything is ok.
```
# use setting proxy
setting = SettingProxy(setting, yamlfile)
results = setting.apply(method)
# directly define setting
setting = ClassIncrementalSetting(dataset="synbols", nb_tasks=12)
results = setting.apply(method)
```

**Comment by lebrice** [comment]
Interesting! Thanks for posting! I'll take a look!

**Comment by lebrice** [comment]
Hey @wwd29  did you place those statements inside of an `if __name__ == "__main__":` block?

**Comment by wwd29** [comment]
> Hey @wwd29 did you place those statements inside of an `if __name__ == "__main__":` block?

Yes, just simply replace the setting definition without other modifications.

**Comment by lebrice** [comment]
Alright thanks, just thought I'd ask.
I was able to reproduce this, although there aren't any issues with the iteration on my end, however I do get a bunch of messages coming from ignored exceptions in the `__del__` of the dataloader workers.
I think it might possibly be due to some interaction between `tqdm` and pytorch (as described here: https://github.com/pytorch/pytorch/issues/53703) but I'll look deeper, see if that really is the issue.

**Comment by wwd29** [comment]
@lebrice Hey, i found it. Just commet this line, it will not create much more new env. 
https://github.com/lebrice/Sequoia/blob/00e09f08cc50f78c2e73233c6f1a1ca930ca0978/sequoia/client/env_proxy.py#L75

**Comment by lebrice** [comment]
Thanks @wwd29 , I'll add some tests for env_proxy, just to make sure that this doesn't change anything with either the SL or RL tracks of the competition.
