### ISSUE TITLE
Error in argparse when running CRL settings

### ISSUE THREAD

**Issue by Dumail** [lebrice/Sequoia#259]
When attempting to run for CRL settings,  such as ```sequoia run incremental_rl –nb_tasks 5 --method sb3.ppo --steps_per_task 10_000``` command, an error occurs in argparse. 
The error message reads ```In argparse, nargs=0 parses an empty list, and nargs=1 is list of bools with one item, not a required single boolean```.
* Python version: 3.8.2
* Operating system: Ubuntu 20.04

**Comment by lebrice** [comment]
Hi @Dumail , I fixed the issue. Here's the command you can use:

```console
sequoia run incremental_rl --nb_tasks=5 --train_steps_per_task=10_000 sb3.ppo
```
This is generally like this:
`sequoia run <setting> <setting args> <method> <method args>`. Let me know if you have any other issues!
